-- todo: 替換 USER
CREATE USER temp_own WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD '!QAZ 0okm 8uhb';

-- todo: 替換 USER
CREATE USER temp_write WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD '!QAZ 0okm 8uhb';

-- todo: 替換 資料庫名稱 及 OWNER
CREATE DATABASE template
  WITH
  OWNER = temp_own
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;